package multiagentbaseddevelopersupportsystem.service;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import multiagentbaseddevelopersupportsystem.domain.Post;
import multiagentbaseddevelopersupportsystem.domain.PostRepository;
import multiagentbaseddevelopersupportsystem.domain.PostResponseDto;
import multiagentbaseddevelopersupportsystem.external.attachment.AttachmentClient;
import multiagentbaseddevelopersupportsystem.external.attachment.AttachmentDto;
import multiagentbaseddevelopersupportsystem.external.ai.AiAgentClient;
import multiagentbaseddevelopersupportsystem.external.ai.AiGenerateRequest;
import multiagentbaseddevelopersupportsystem.external.ai.AiGenerateResponse;

import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

@Service
@Transactional
@RequiredArgsConstructor
public class PostAutoGenerateService {

    private final PostRepository postRepository;
    private final AttachmentClient attachmentClient;
    private final AiAgentClient aiAgentClient;

    @Value("${attachment.base-url}")
    private String attachmentBaseUrl; // 예: http://localhost:8089

    public PostResponseDto autoGenerateFromAttachments(Long userId, Long postId) {
        Post post = findAndCheckAuthor(userId, postId);

        // 1) 첨부 목록 조회 (Attachment 서비스 호출)
        List<AttachmentDto> files = attachmentClient.getFilesByPostId(postId);
        if (files == null || files.isEmpty()) {
            throw new IllegalStateException("첨부 파일이 없습니다. 파일 업로드 후 다시 시도해 주세요.");
        }

        // 2) 다운로드 가능한 URL 목록 생성
        List<String> urls = files.stream()
                .map(this::buildDownloadUrl)
                .filter(Objects::nonNull)
                .collect(Collectors.toList());

        // 3) FastAPI 호출
        AiGenerateRequest req = new AiGenerateRequest(postId, urls, null);
        AiGenerateResponse res = aiAgentClient.generateFromFiles(req);

        // 4) 결과 저장
        post.setTitle(res.getTitle());
        post.setContent(res.getContent());
        // post.setAutoGenerated(true); // 엔티티에 필드가 있으면 사용

        return postRepository.save(post).toDto();
    }

    private Post findAndCheckAuthor(Long userId, Long postId) {
        Post post = postRepository.findById(postId)
                .orElseThrow(() -> new RuntimeException("게시글을 찾을 수 없습니다. id=" + postId));
        if (!Objects.equals(post.getUserId(), userId)) {
            throw new RuntimeException("해당 게시글에 대한 수정 권한이 없습니다.");
        }
        return post;
    }

    private String buildDownloadUrl(AttachmentDto a) {
        // Azure 등 절대 URL이면 그대로 사용
        if (a.getFileUrl() != null && a.getFileUrl().startsWith("http")) {
            return a.getFileUrl();
        }
        // 로컬 저장소면 다운로드 API 경로로 조합
        if (a.getStoredName() != null) {
            return attachmentBaseUrl + "/attachments/download/" + a.getStoredName();
        }
        return null;
    }
}
