name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./usermanagement/pom.xml
          mvn clean package -f ./codeassistant/pom.xml
          mvn clean package -f ./task/pom.xml
          mvn clean package -f ./communication/pom.xml
          mvn clean package -f ./schedule/pom.xml
          mvn clean package -f ./notification/pom.xml
          mvn clean package -f ./board/pom.xml

      - name: Docker Build and push for Usermanagement
        uses: docker/build-push-action@v4
        with:
          context: ./usermanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/usermanagement:latest
            ghcr.io/${{ github.repository }}/usermanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Codeassistant
        uses: docker/build-push-action@v4
        with:
          context: ./codeassistant
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/codeassistant:latest
            ghcr.io/${{ github.repository }}/codeassistant:${{ github.ref_name }}
            
      - name: Docker Build and push for Task
        uses: docker/build-push-action@v4
        with:
          context: ./task
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/task:latest
            ghcr.io/${{ github.repository }}/task:${{ github.ref_name }}
            
      - name: Docker Build and push for Communication
        uses: docker/build-push-action@v4
        with:
          context: ./communication
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/communication:latest
            ghcr.io/${{ github.repository }}/communication:${{ github.ref_name }}
            
      - name: Docker Build and push for Schedule
        uses: docker/build-push-action@v4
        with:
          context: ./schedule
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/schedule:latest
            ghcr.io/${{ github.repository }}/schedule:${{ github.ref_name }}
            
      - name: Docker Build and push for Notification
        uses: docker/build-push-action@v4
        with:
          context: ./notification
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/notification:latest
            ghcr.io/${{ github.repository }}/notification:${{ github.ref_name }}
            
      - name: Docker Build and push for Board
        uses: docker/build-push-action@v4
        with:
          context: ./board
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/board:latest
            ghcr.io/${{ github.repository }}/board:${{ github.ref_name }}
            
