server:
  port: 8088

jwt:
  header: Authorization
  headerPrefix: Bearer
  secret: ${JWT_SECRET_KEY}
---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: usermanagement
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**,/users/**
        - id: codeassistant
          uri: http://localhost:8083
          predicates:
            - Path=, 
        - id: invitemanagement
          uri: http://localhost:8084
          predicates:
            - Path=/invites/**, 
        - id: communication
          uri: http://localhost:8085
          predicates:
            - Path=, 
        - id: projectmanagement
          uri: http://localhost:8089
          predicates:
            - Path=/projectManagements/**
        - id: schedule
          uri: http://localhost:8086
          predicates:
            - Path=/calendars/**, 
        - id: notification
          uri: http://localhost:8087
          predicates:
            - Path=/notifications/**, 
        - id: post
          uri: http://localhost:8090
          predicates:
            - Path=/posts/**
          filters:
            - JwtAuth
        - id: attachment
          uri: http://localhost:8091
          predicates:
            - Path=/attachments/**
          filters:
            - JwtAuth
        - id: comment
          uri: http://localhost:8092
          predicates:
            - Path=/comments/**
          filters:
            - JwtAuth
        - id: agent-fastapi
          uri: http://center-agent-service:8003
          predicates:
            - Path=/ai/**
        - id: frontend
          uri: http://localhost:3000
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
              - "http://192.168.*.*:3000"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
logging:
  level:
    multiagentbaseddevelopersupportsystem: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    root: INFO

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: usermanagement
          uri: http://usermanagement:8080
          predicates:
            - Path=/auth/**,/users/**
        - id: codeassistant
          uri: http://codeassistant:8080
          predicates:
            - Path=, 
        - id: task
          uri: http://task:8080
          predicates:
            - Path=/taskAssignments/**, 
        - id: communication
          uri: http://communication:8080
          predicates:
            - Path=, 
        - id: projectmanagement
          uri: http://projectmanagement:8080
          predicates:
            - Path=/projectManagements/**
        - id: schedule
          uri: http://schedule:8080
          predicates:
            - Path=/calendars/**, 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, 
        - id: post
          uri: http://post:8080
          predicates:
            - Path=/posts/**
          filters:
            - JwtAuth
        - id: attachment
          uri: http://attachment:8080
          predicates:
            - Path=/attachments/**
          filters:
            - JwtAuth
        - id: comment
          uri: http://comment:8080
          predicates:
            - Path=/comments/**
          filters:
            - JwtAuth 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
        - id: invitemanagement
          uri: http://inviteManagement:8080
          predicates:
            - Path=/invites/**, 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080


