apiVersion: apps/v1
kind: Deployment
metadata:
  name: attachment
  labels:
    app: attachment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attachment
  template:
    metadata:
      labels:
        app: attachment
    spec:
      containers:
        - name: attachment
          image: "bigproject.azurecr.io/attachment:v7"
          env:
            - name: AZURE_MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: url
            - name: AZURE_MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: AZURE_MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: password
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: azure-storage-account-name
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: azure-storage-account-key
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-storage-secret
                  key: azure-storage-container-name
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
