apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeassistant
  labels:
    app: codeassistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeassistant
  template:
    metadata:
      labels:
        app: codeassistant
    spec:
      containers:
        - name: codeassistant
          image: "username/codeassistant:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
